from dashboard.routes.base import *
from dashboard.routes.data_management import *
from dashboard.routes.mapper import *
from dashboard.routes.metrics import *
from dashboard.routes.mobile_user import *
from dashboard.routes.new_survey import *
from dashboard.routes.new_web_user import *
from dashboard.routes.prompts import *
from dashboard.routes.settings import *
from dashboard.routes.survey import *
from dashboard.routes.web_user import *
